#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = subdirs
PATHS *= \
    . \
    ./lib \
    ./modules \
    ./include \
    ./bin \


DEPENDPATH *= $$PATHS

include($$PWD/modules/core/core.pro)
include($$PWD/modules/math/math.pro)
include($$PWD/modules/contour/contour.pro)
include($$PWD/modules/sample/sample.pro)
