#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TARGET = contour

QT =

OBJECTS_DIR = objects

SOURCES *= \
    $$PWD/src/contour.cpp

HEADERS *= \
    $$PWD/include/contour.h

PATHS *= \
    $$PWD \
    $$PWD/src \
    $$PWD/include

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
