#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TARGET = features

QT =

OBJECTS_DIR = objects


SOURCES *= \
    $$PWD/src/graphic_pillars.cpp

HEADERS *= \
    $$PWD/include/graphic_pillars.h

PATHS *= \
    $$PWD \
    $$PWD/src \
    $$PWD/include

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
