#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = sample

QT =

OBJECTS_DIR = objects

SOURCES *= \
    $$PWD/src/main.cpp

PATHS *= \
    $$PWD \
    $$PWD/src \
    $$PWD/include \
#    $$_PRO_FILE_PWD_/include \


DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

DESTDIR = bin
